[workspace]
resolver = "3"
members = ["crates/*", "crates/llm/deepseek"]

[workspace.package]
version = "0.0.9"
edition = "2024"
authors = ["clearloop <tianyi.gc@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/clearloop/cydonia"
keywords = ["llm", "agent", "ai"]

[workspace.dependencies]
deepseek = { path = "crates/llm/deepseek", package = "cydonia-deepseek", version = "0.0.9" }
llm = { path = "crates/llm", package = "cydonia-llm", version = "0.0.9" }
agent = { path = "crates/agent", package = "cydonia-agent", version = "0.0.9" }
runtime = { path = "crates/runtime", package = "cydonia-runtime", version = "0.0.9" }

# crates.io
anyhow = "1"
async-stream = "0.3"
futures-core = "0.3"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }
schemars = "1.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
