[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1"
candle-core = "0.8.1"
candle-nn = "0.8.1"
candle-transformers = "0.8.1"
clap = "4.5.23"
dirs = "5.0.1"
hf-hub = "0.4.1"
llamac-sys = { version = "0.1.86", package = "llama-cpp-sys-2" }
once_cell = "1.20.2"
serde = "1.0.217"
serde_json = "1.0.134"
tokenizers = "0.21.0"
toml = "0.8.19"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
