[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
ccore = { path = "crates/core", package = "cydonia-core" }
candle = { path = "crates/candle", package = "cydonia-candle" }

# crates.io
anyhow = "1"
candle-core = { version = "0.8.1", features = ["accelerate"] }
candle-nn = { version = "0.8.1", features = ["accelerate"] }
candle-transformers = { version = "0.8.1", features = ["accelerate"] }
clap = "4.5.23"
dirs = "5.0.1"
hf-hub = "0.4.1"
llamac-sys = { version = "0.1.86", package = "llama-cpp-sys-2" }
once_cell = "1.20.2"
rand = "0.8.5"
serde = "1.0.217"
serde_json = "1.0.134"
tokenizers = "0.21.0"
toml = "0.8.19"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
