[workspace]
resolver = "3"
members = ["crates/*", "crates/llm/deepseek", "legacy/*"]

[workspace.package]
version = "0.0.9"
edition = "2024"
authors = ["clearloop <tianyi.gc@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/clearloop/cydonia"
keywords = ["llm", "agent", "ai"]

[workspace.dependencies]
candle = { path = "crates/candle", package = "cydonia-candle", version = "0.0.9" }
cli = { path = "crates/cli", package = "cydonia-cli", version = "0.0.9" }
deepseek = { path = "crates/llm/deepseek", package = "cydonia-deepseek", version = "0.0.9" }
llm = { path = "crates/llm", package = "cydonia-llm", version = "0.0.9" }
model = { path = "legacy/model", package = "cydonia-model", version = "0.0.9" }
cydonia = { path = "crates/cydonia", version = "0.0.9" }
agent = { path = "crates/agent", package = "cydonia-agent", version = "0.0.9" }
runtime = { path = "crates/runtime", package = "cydonia-runtime", version = "0.0.9" }

# crates.io
anyhow = "1"
chrono = "0.4"
async-stream = "0.3"
clap = { version = "4.5", features = ["derive"] }
dirs = "6"
futures-core = "0.3"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }
schemars = "1.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
toml = "0.9.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }


# legacy dependencies
candle-core = "0.8.1"
candle-nn = "0.8.1"
candle-transformers = "0.8.1"
hf-hub = "0.4.1"
llamac-sys = { version = "0.1.86", package = "llama-cpp-sys-2" }
once_cell = "1.21"
rand = "0.9.2"
tokenizers = "0.21.0"

[workspace.metadata.conta]
packages = ["agent", "deepseek", "cydonia", "cli"]
