[workspace]
resolver = "3"
members = ["app/cli", "app/client","app/gateway", "app/hub","crates/*", "crates/llm/deepseek"]

[workspace.package]
version = "0.0.9"
edition = "2024"
authors = ["clearloop <tianyi.gc@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/clearloop/walrus"
keywords = ["llm", "agent", "ai"]

[workspace.dependencies]
deepseek = { path = "crates/llm/deepseek", package = "walrus-deepseek", version = "0.0.9" }
llm = { path = "crates/llm", package = "walrus-llm", version = "0.0.9" }
agent = { path = "crates/core", package = "walrus-core", version = "0.0.9" }
runtime = { path = "crates/runtime", package = "walrus-runtime", version = "0.0.9" }
sqlite = { path = "crates/sqlite", package = "walrus-sqlite", version = "0.0.9" }
telegram = { path = "crates/telegram", package = "walrus-telegram", version = "0.0.9" }

# crates.io
anyhow = "1"
async-stream = "0.3"
bytes = "1"
compact_str = { version = "0.8", features = ["serde"] }
futures-core = "0.3"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }
rmcp = { version = "0.16", features = ["client", "transport-child-process"] }
rusqlite = { version = "0.34", features = ["bundled"] }
schemars = "1.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
smallvec = { version = "1", features = ["serde"] }
tempfile = "3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
