[package]
name = "walrus-runtime"
description = "Walrus runtime"
documentation = "https://docs.rs/walrus-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
llm.workspace = true
wcore.workspace = true

# crates-io dependencies
anyhow.workspace = true
compact_str.workspace = true
async-stream.workspace = true
futures-core.workspace = true
futures-util.workspace = true
reqwest.workspace = true
rmcp.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
deepseek.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
chrono.workspace = true
