[package]
name = "walrus-sqlite"
description = "SQLite-backed memory for Walrus agents"
documentation = "https://docs.rs/walrus-sqlite"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
wcore.workspace = true
anyhow.workspace = true
compact_str.workspace = true
rusqlite.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
