[package]
name = "ullm-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true

[[bin]]
name = "ullm"
path = "bin/ullm.rs"

[dependencies]
ullm.workspace = true

# crates-io dependencies
anyhow.workspace = true
clap.workspace = true
dirs.workspace = true
futures-util.workspace = true
serde.workspace = true
toml.workspace = true
schemars.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
