[package]
name = "deepseek"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true

[dependencies]
ucore.workspace = true

# crates-io dependencies
anyhow.workspace = true
