[package]
name = "walrus-local"
description = "Walrus local LLM provider via mistralrs"
documentation = "https://docs.rs/walrus-local"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
llm.workspace = true
anyhow.workspace = true
async-stream.workspace = true
compact_str.workspace = true
futures-core.workspace = true
serde_json.workspace = true
tracing.workspace = true
mistralrs.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
mistralrs = { workspace = true, features = ["metal", "accelerate"] }
