[package]
name = "cydonia-service"
version = "0.0.0"
edition = "2021"
description = "The service crate for the cydonia network."

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
