[package]
name = "cydonia-model"
version = "0.0.0"
edition = "2021"
description = "Cydonia Models"

[dependencies]
anyhow.workspace = true
candle-core.workspace = true
candle-nn.workspace = true
candle-transformers.workspace = true
ccore.workspace = true
clap = { workspace = true, features = ["derive"] }
dirs.workspace = true
hf-hub.workspace = true
once_cell.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokenizers.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
