[package]
name = "cydonia-core"
description = "Cydonia core abstractions"
documentation = "https://docs.rs/cydonia-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
derive_more.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-core.workspace = true
futures-util.workspace = true
reqwest.workspace = true
schemars.workspace = true
