[package]
name = "cydonia-memory"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
description = "Cydonia persistent memory"

[dependencies]
anyhow.workspace = true
ccore.workspace = true
