[package]
name = "cydonia-llm"
description = "Cydonia unified LLM interface"
documentation = "https://docs.rs/cydonia-llm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-core.workspace = true
futures-util.workspace = true
reqwest.workspace = true
schemars.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
