[package]
name = "walrus-llm"
description = "Walrus unified LLM interface"
documentation = "https://docs.rs/walrus-llm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[features]
default = ["http"]
http = ["dep:reqwest", "dep:futures-util"]

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
compact_str.workspace = true
serde.workspace = true
smallvec.workspace = true
serde_json.workspace = true
futures-core.workspace = true
futures-util = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
schemars.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
